package com.upsee.katachi.ime

// 自動生成: core/data/romaji.ts と core/data/godan.ts から web の build:data が
// 書き出す。直接編集しないこと。
object Romaji {
    /** ローマ字 -> かな。最長一致で引く */
    val TABLE: Map<String, String> = mapOf(
        "a" to "あ",
        "i" to "い",
        "u" to "う",
        "e" to "え",
        "o" to "お",
        "ka" to "か",
        "ki" to "き",
        "ku" to "く",
        "ke" to "け",
        "ko" to "こ",
        "ga" to "が",
        "gi" to "ぎ",
        "gu" to "ぐ",
        "ge" to "げ",
        "go" to "ご",
        "sa" to "さ",
        "si" to "し",
        "shi" to "し",
        "su" to "す",
        "se" to "せ",
        "so" to "そ",
        "za" to "ざ",
        "zi" to "じ",
        "ji" to "じ",
        "zu" to "ず",
        "ze" to "ぜ",
        "zo" to "ぞ",
        "ta" to "た",
        "ti" to "ち",
        "chi" to "ち",
        "tu" to "つ",
        "tsu" to "つ",
        "te" to "て",
        "to" to "と",
        "da" to "だ",
        "di" to "ぢ",
        "du" to "づ",
        "de" to "で",
        "do" to "ど",
        "na" to "な",
        "ni" to "に",
        "nu" to "ぬ",
        "ne" to "ね",
        "no" to "の",
        "ha" to "は",
        "hi" to "ひ",
        "hu" to "ふ",
        "fu" to "ふ",
        "he" to "へ",
        "ho" to "ほ",
        "ba" to "ば",
        "bi" to "び",
        "bu" to "ぶ",
        "be" to "べ",
        "bo" to "ぼ",
        "pa" to "ぱ",
        "pi" to "ぴ",
        "pu" to "ぷ",
        "pe" to "ぺ",
        "po" to "ぽ",
        "ma" to "ま",
        "mi" to "み",
        "mu" to "む",
        "me" to "め",
        "mo" to "も",
        "ya" to "や",
        "yu" to "ゆ",
        "yo" to "よ",
        "ye" to "いぇ",
        "ra" to "ら",
        "ri" to "り",
        "ru" to "る",
        "re" to "れ",
        "ro" to "ろ",
        "wa" to "わ",
        "wi" to "うぃ",
        "we" to "うぇ",
        "wo" to "を",
        "nn" to "ん",
        "n'" to "ん",
        "kya" to "きゃ",
        "kyu" to "きゅ",
        "kyo" to "きょ",
        "kye" to "きぇ",
        "gya" to "ぎゃ",
        "gyu" to "ぎゅ",
        "gyo" to "ぎょ",
        "sha" to "しゃ",
        "shu" to "しゅ",
        "sho" to "しょ",
        "she" to "しぇ",
        "sya" to "しゃ",
        "syu" to "しゅ",
        "syo" to "しょ",
        "ja" to "じゃ",
        "ju" to "じゅ",
        "jo" to "じょ",
        "je" to "じぇ",
        "jya" to "じゃ",
        "jyu" to "じゅ",
        "jyo" to "じょ",
        "zya" to "じゃ",
        "zyu" to "じゅ",
        "zyo" to "じょ",
        "cha" to "ちゃ",
        "chu" to "ちゅ",
        "cho" to "ちょ",
        "che" to "ちぇ",
        "tya" to "ちゃ",
        "tyu" to "ちゅ",
        "tyo" to "ちょ",
        "nya" to "にゃ",
        "nyu" to "にゅ",
        "nyo" to "にょ",
        "hya" to "ひゃ",
        "hyu" to "ひゅ",
        "hyo" to "ひょ",
        "bya" to "びゃ",
        "byu" to "びゅ",
        "byo" to "びょ",
        "pya" to "ぴゃ",
        "pyu" to "ぴゅ",
        "pyo" to "ぴょ",
        "mya" to "みゃ",
        "myu" to "みゅ",
        "myo" to "みょ",
        "rya" to "りゃ",
        "ryu" to "りゅ",
        "ryo" to "りょ",
        "fa" to "ふぁ",
        "fi" to "ふぃ",
        "fe" to "ふぇ",
        "fo" to "ふぉ",
        "va" to "ゔぁ",
        "vi" to "ゔぃ",
        "vu" to "ゔ",
        "ve" to "ゔぇ",
        "vo" to "ゔぉ",
        "tsa" to "つぁ",
        "tsi" to "つぃ",
        "tse" to "つぇ",
        "tso" to "つぉ",
        "dya" to "ぢゃ",
        "dyu" to "ぢゅ",
        "dyo" to "ぢょ",
        "xa" to "ぁ",
        "xi" to "ぃ",
        "xu" to "ぅ",
        "xe" to "ぇ",
        "xo" to "ぉ",
        "la" to "ぁ",
        "li" to "ぃ",
        "lu" to "ぅ",
        "le" to "ぇ",
        "lo" to "ぉ",
        "xtu" to "っ",
        "ltu" to "っ",
        "xya" to "ゃ",
        "xyu" to "ゅ",
        "xyo" to "ょ",
        "-" to "ー",
    )
}

object Godan {
    /** chars は [中央, 左, 上, 右, 下]。中身はローマ字 */
    data class Key(val label: String, val chars: List<String>)

    private fun key(
        center: String,
        left: String = "",
        up: String = "",
        right: String = "",
        down: String = "",
    ) = Key(center.uppercase(), listOf(center, left, up, right, down))

    /** 左列に母音・中央と右に子音の3列5段 */
    val ROWS: List<List<Key>> = listOf(
        listOf(key("a", "", "", "", ""), key("k", "", "c", "g", ""), key("h", "p", "f", "b", "")),
        listOf(key("i", "", "", "", ""), key("s", "sh", "j", "z", ""), key("m", "", "", "", "")),
        listOf(key("u", "", "", "", ""), key("t", "ts", "ch", "d", ""), key("y", "", "", "", "")),
        listOf(key("e", "", "", "", ""), key("n", "", "", "", ""), key("r", "", "", "", "")),
        listOf(key("o", "", "", "", ""), Key("小゛゜", emptyList()), key("w", "", "", "", "")),
    )
}
