import Foundation

// 自動生成: core/data/romaji.ts と core/data/godan.ts から web の build:data が
// 書き出す。直接編集しないこと。
enum Romaji {
    /// ローマ字 -> かな。最長一致で引く
    static let table: [String: String] = [
        "a": "あ",
        "i": "い",
        "u": "う",
        "e": "え",
        "o": "お",
        "ka": "か",
        "ki": "き",
        "ku": "く",
        "ke": "け",
        "ko": "こ",
        "ga": "が",
        "gi": "ぎ",
        "gu": "ぐ",
        "ge": "げ",
        "go": "ご",
        "sa": "さ",
        "si": "し",
        "shi": "し",
        "su": "す",
        "se": "せ",
        "so": "そ",
        "za": "ざ",
        "zi": "じ",
        "ji": "じ",
        "zu": "ず",
        "ze": "ぜ",
        "zo": "ぞ",
        "ta": "た",
        "ti": "ち",
        "chi": "ち",
        "tu": "つ",
        "tsu": "つ",
        "te": "て",
        "to": "と",
        "da": "だ",
        "di": "ぢ",
        "du": "づ",
        "de": "で",
        "do": "ど",
        "na": "な",
        "ni": "に",
        "nu": "ぬ",
        "ne": "ね",
        "no": "の",
        "ha": "は",
        "hi": "ひ",
        "hu": "ふ",
        "fu": "ふ",
        "he": "へ",
        "ho": "ほ",
        "ba": "ば",
        "bi": "び",
        "bu": "ぶ",
        "be": "べ",
        "bo": "ぼ",
        "pa": "ぱ",
        "pi": "ぴ",
        "pu": "ぷ",
        "pe": "ぺ",
        "po": "ぽ",
        "ma": "ま",
        "mi": "み",
        "mu": "む",
        "me": "め",
        "mo": "も",
        "ya": "や",
        "yu": "ゆ",
        "yo": "よ",
        "ye": "いぇ",
        "ra": "ら",
        "ri": "り",
        "ru": "る",
        "re": "れ",
        "ro": "ろ",
        "wa": "わ",
        "wi": "うぃ",
        "we": "うぇ",
        "wo": "を",
        "nn": "ん",
        "n'": "ん",
        "kya": "きゃ",
        "kyu": "きゅ",
        "kyo": "きょ",
        "kye": "きぇ",
        "gya": "ぎゃ",
        "gyu": "ぎゅ",
        "gyo": "ぎょ",
        "sha": "しゃ",
        "shu": "しゅ",
        "sho": "しょ",
        "she": "しぇ",
        "sya": "しゃ",
        "syu": "しゅ",
        "syo": "しょ",
        "ja": "じゃ",
        "ju": "じゅ",
        "jo": "じょ",
        "je": "じぇ",
        "jya": "じゃ",
        "jyu": "じゅ",
        "jyo": "じょ",
        "zya": "じゃ",
        "zyu": "じゅ",
        "zyo": "じょ",
        "cha": "ちゃ",
        "chu": "ちゅ",
        "cho": "ちょ",
        "che": "ちぇ",
        "tya": "ちゃ",
        "tyu": "ちゅ",
        "tyo": "ちょ",
        "nya": "にゃ",
        "nyu": "にゅ",
        "nyo": "にょ",
        "hya": "ひゃ",
        "hyu": "ひゅ",
        "hyo": "ひょ",
        "bya": "びゃ",
        "byu": "びゅ",
        "byo": "びょ",
        "pya": "ぴゃ",
        "pyu": "ぴゅ",
        "pyo": "ぴょ",
        "mya": "みゃ",
        "myu": "みゅ",
        "myo": "みょ",
        "rya": "りゃ",
        "ryu": "りゅ",
        "ryo": "りょ",
        "fa": "ふぁ",
        "fi": "ふぃ",
        "fe": "ふぇ",
        "fo": "ふぉ",
        "va": "ゔぁ",
        "vi": "ゔぃ",
        "vu": "ゔ",
        "ve": "ゔぇ",
        "vo": "ゔぉ",
        "tsa": "つぁ",
        "tsi": "つぃ",
        "tse": "つぇ",
        "tso": "つぉ",
        "dya": "ぢゃ",
        "dyu": "ぢゅ",
        "dyo": "ぢょ",
        "xa": "ぁ",
        "xi": "ぃ",
        "xu": "ぅ",
        "xe": "ぇ",
        "xo": "ぉ",
        "la": "ぁ",
        "li": "ぃ",
        "lu": "ぅ",
        "le": "ぇ",
        "lo": "ぉ",
        "xtu": "っ",
        "ltu": "っ",
        "xya": "ゃ",
        "xyu": "ゅ",
        "xyo": "ょ",
        "-": "ー",
    ]
}

enum Godan {
    /// chars は [中央, 左, 上, 右, 下]。中身はローマ字
    struct Key {
        let label: String
        let chars: [String]
    }

    private static func key(
        _ center: String, _ left: String = "", _ up: String = "",
        _ right: String = "", _ down: String = "",
    ) -> Key {
        Key(label: center.uppercased(), chars: [center, left, up, right, down])
    }

    /// 左列に母音・中央と右に子音の3列5段
    static let rows: [[Key]] = [
        [key("a", "", "", "", ""), key("k", "", "c", "g", ""), key("h", "p", "f", "b", "")],
        [key("i", "", "", "", ""), key("s", "sh", "j", "z", ""), key("m", "", "", "", "")],
        [key("u", "", "", "", ""), key("t", "ts", "ch", "d", ""), key("y", "", "", "", "")],
        [key("e", "", "", "", ""), key("n", "", "", "", ""), key("r", "", "", "", "")],
        [key("o", "", "", "", ""), Key(label: "小゛゜", chars: []), key("w", "", "", "", "")],
    ]
}
